name: meu_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.1.0
  
  # Gerenciamento de estado
  provider: ^6.1.1
  
  # Autenticação (desabilitada temporariamente para build Windows)
  # firebase_core: ^2.24.2
  # firebase_auth: ^4.15.3
  # google_sign_in: ^6.1.6
  
  # Utilitários
  shared_preferences: ^2.2.2
  percent_indicator: ^4.2.3
  intl: ^0.19.0
  
  # Ícones
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^7.1.2
  cloud_firestore: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/apple.png
    - assets/images/chart.png
    - assets/images/fox.png
    - assets/images/hat.png